app = "openlistat"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5244"
  TZ = "Asia/Shanghai"

[http_service]
  internal_port = 5244
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

[[mounts]]
  source = "openlist_data"
  destination = "/opt/openlist/data"
